label: SEO
icon: search
columns:
	- width: 1/1
		sections:
			og_image_custom:
				type: fields
				width: 2/3
				fields:
					extends: fields/seo/og_image
			og_image_preview:
				type: og_image_preview
				sticky: true
				width: 1/3
	- width: 1/1
		sections:
			seo_content:
				type: fields
				width: 2/3
				fields:
					extends: fields/seo
			google_preview:
				type: google_preview
				sticky: true
				width: 1/3
